[pytest]
addopts = -s -v
norecursedirs = my-example-autotests-api
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    items: Тесты объявлений.
    statistics: Тесты статистики.
    regression: Регрессионные тесты.
    e2e: Сквозные тесты.
    negative: Негативные тесты.
    smoke: Smoke-тесты.
    security: Тесты безопасности.
